# ── Base de Dados ──────────────────────────────────────────────────────────────
spring.datasource.url=jdbc:postgresql://localhost:5432/Neo-Cerveja
spring.datasource.username=postgres
spring.datasource.password=psql
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10

# ── Spring Boot ────────────────────────────────────────────────────────────────
spring.main.web-application-type=servlet
spring.main.banner-mode=off
server.port=8080

# ── Logging ────────────────────────────────────────────────────────────────────
logging.level.root=WARN
logging.level.com.gestorcerveja=INFO
